exec-once = hyprpaper &
exec-once = hyprpm reload & 
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#exec-once = ironbar &
