# If you want a wallpaper that doesn't change everytime the system reloads
# preload = /home/rose/.config/walls/wallhaven-rrljjq.jpg
# wallpaper = eDP-1, /home/rose/.config/walls/wallhaven-rrljjq.jpg
ipc = true
wallpaper{
  monitor = 
  path = /home/rose/.config/walls
  timeout = 300
}
