$font = Liga DM Mono

general {
    hide_cursor = true
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 1
}

input-field {
    monitor =
    size = 15%, 5%
    outline_thickness = 0
    inner_color = rgba(40, 40, 40, 1.0)
    outer_color = rgba(51, 51, 51, 1.0)
    check_color = rgba(180, 150, 150, 1.0)

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 0

    font_family = $font
    placeholder_text = Your system is mine now
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    dots_text_format = õ

    hide_input = true

    position = 0, -50
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = center
    valign = top
}
